import express from 'express';
import authRoutes from './auth';
import userRoutes from './users';
import hospitalRoutes from './hospitals';
import branchRoutes from './branches';
import subscriptionRoutes from './subscription-plans';
import subscriptionsRoutes from './subscriptions';
import supportRoutes from './support';
import knowledgeBaseRoutes from './knowledge-base';
import billingRoutes from './billing';
import financialRoutes from './financial';
import patientRoutes from './patients';
import paymentRoutes from './payments';
import appointmentRoutes from './appointments';
import departmentRoutes from './departments';
import analyticsRoutes from './analytics';
import auditRoutes from './audit';
import complianceRoutes from './compliance';
import doctorAvailabilityRoutes from './doctor-availability';
import notificationRoutes from './notifications';
import chatRoutes from './chat';
import ehrRoutes from './ehr';
import prescriptionRoutes from './prescriptions';
import masterAdminRoutes from './master-admin';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/hospitals', hospitalRoutes);
router.use('/branches', branchRoutes);
router.use('/subscription-plans', subscriptionRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/support', supportRoutes);
router.use('/knowledge-base', knowledgeBaseRoutes);
router.use('/billing', billingRoutes);
router.use('/financial', financialRoutes);
router.use('/patients', patientRoutes);
router.use('/payments', paymentRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/departments', departmentRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/audit', auditRoutes);
router.use('/compliance', complianceRoutes);
router.use('/doctor-availability', doctorAvailabilityRoutes);
router.use('/notifications', notificationRoutes);
router.use('/chat', chatRoutes);
router.use('/ehr', ehrRoutes);
router.use('/prescriptions', prescriptionRoutes);
router.use('/master-admin', masterAdminRoutes);

export default router; 