"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Receipt = void 0;
var mongoose_1 = __importStar(require("mongoose"));
var receiptSchema = new mongoose_1.Schema({
    receiptNumber: {
        type: String,
        required: [true, 'Receipt number is required'],
        unique: true,
        index: true
    },
    paymentId: {
        type: mongoose_1.Schema.Types.ObjectId,
        ref: 'Payment',
        required: [true, 'Payment ID is required']
    },
    patientId: {
        type: mongoose_1.Schema.Types.ObjectId,
        ref: 'Patient',
        required: [true, 'Patient ID is required']
    },
    appointmentId: {
        type: mongoose_1.Schema.Types.ObjectId,
        ref: 'Appointment'
    },
    amount: {
        type: Number,
        required: [true, 'Amount is required'],
        min: [0, 'Amount cannot be negative']
    },
    paymentMethod: {
        type: String,
        required: [true, 'Payment method is required'],
        enum: ['cash', 'card', 'insurance']
    },
    paymentStatus: {
        type: String,
        required: true,
        enum: ['pending', 'completed', 'refunded']
    },
    generatedBy: {
        type: mongoose_1.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Generated by user ID is required']
    },
    generatedAt: {
        type: Date,
        default: Date.now
    },
    pdfUrl: {
        type: String
    },
    metadata: {
        patientName: {
            type: String,
            required: [true, 'Patient name is required']
        },
        patientPhone: {
            type: String,
            required: [true, 'Patient phone is required']
        },
        doctorName: String,
        doctorSpecialization: String,
        appointmentDate: Date,
        appointmentType: String,
        receptionistName: {
            type: String,
            required: [true, 'Receptionist name is required']
        }
    }
}, {
    timestamps: true
});
// Create indexes for better query performance
receiptSchema.index({ paymentId: 1 });
receiptSchema.index({ patientId: 1 });
receiptSchema.index({ appointmentId: 1 });
receiptSchema.index({ generatedBy: 1 });
receiptSchema.index({ generatedAt: -1 });
receiptSchema.index({ 'metadata.patientName': 1 });
receiptSchema.index({ 'metadata.doctorName': 1 });
// Virtual populate for related data
receiptSchema.virtual('payment', {
    ref: 'Payment',
    localField: 'paymentId',
    foreignField: '_id',
    justOne: true
});
receiptSchema.virtual('patient', {
    ref: 'Patient',
    localField: 'patientId',
    foreignField: '_id',
    justOne: true
});
receiptSchema.virtual('appointment', {
    ref: 'Appointment',
    localField: 'appointmentId',
    foreignField: '_id',
    justOne: true
});
receiptSchema.virtual('generator', {
    ref: 'User',
    localField: 'generatedBy',
    foreignField: '_id',
    justOne: true
});
// Ensure virtuals are included in JSON output
receiptSchema.set('toJSON', { virtuals: true });
receiptSchema.set('toObject', { virtuals: true });
exports.Receipt = mongoose_1.default.models.Receipt || mongoose_1.default.model('Receipt', receiptSchema);
